### ISSUE TITLE
image_needs_pushing() - is it misbehaving?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#41] opened 2019-09-09 16:24 UTC
## @rodriguez-facundo wrote:

Hi guys, the tag 0.9-b51ffeb for k8s-network-tools and k8s-image-awaiter docker images was overwrite on Saturday. I had a deployment to k8s working with that tag on Friday and today the awaiter is hanging up, unable to deploy a small change I did to my notebook. Any idea how can I get the image that was in that tag before Saturday update?

## Dear rubber duck
I write to you to document and think more clearly...

Hmmmm why did this happen? I verified there was an override of the b51ffeb tag as Facu described, and that this tag was 4 months old relating to jupyterhub 1.0.0.

Hmmm... Neither do I understand how the rebuild caused image-awaiter to get stuck...

## Investigation

In the logs here, i found that there was a push made by chartpress, our CLI helping out: https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/581728271

```
$> docker build -t jupyterhub/k8s-hub:0.9-ec3b97d images/hub --build-arg JUPYTERHUB_VERSION=1.0.0
$> docker push jupyterhub/k8s-hub:0.9-ec3b97d $> git log -n 1 --pretty=format:%h -- images/network-tools chartpress.yaml
$> docker build -t jupyterhub/k8s-network-tools:0.9-b51ffeb images/network-tools
$> docker push jupyterhub/k8s-network-tools:0.9-b51ffeb
$> git log -n 1 --pretty=format:%h -- images/image-awaiter chartpress.yaml
$> docker build -t jupyterhub/k8s-image-awaiter:0.9-b51ffeb images/image-awaiter
$> docker push jupyterhub/k8s-image-awaiter:0.9-b51ffeb
$> git log -n 1 --pretty=format:%h -- images/singleuser-sample chartpress.yaml
$> docker build -t jupyterhub/k8s-singleuser-sample:0.9-b51ffeb images/singleuser-sample --build-arg JUPYTERHUB_VERSION=1.0.0
$> docker push jupyterhub/k8s-singleuser-sample:0.9-b51ffeb
```

Why was this done though? The chartpress command was...

```
chartpress --commit-range 14dd29ab85f1...ec3b97df3f75 --push --publish-chart
```

I note that there was no `--tag` sent, so therefor in the chartpress code i can conclude that the following call to docker push was triggered because `image_needs_pushing(image)` was considered truthy.

```python
    if push:
        if tag or image_needs_pushing(image_spec):
            check_call([ 'docker', 'push', image_spec ])
        else:
            print(f"Skipping push for {image_spec}, already on registry")
```

So why was the image_needs_pushing(image_spec) function truthy!?

```python
@lru_cache()
def image_needs_pushing(image):
    """Return whether an image needs pushing
    Args:
    image (str): the `repository:tag` image to be build.
    Returns:
    True: if image needs to be pushed (not on registry)
    False: if not (already present on registry)
    """
    d = docker_client()
    try:
        d.images.get_registry_data(image)
    except docker.errors.APIError:
        # image not found on registry, needs pushing
        return True
    else:
        return False
```

- Was it because memoization through the functools @lru_cache() somehow returned a cached truthy value while it shouldn't have?
- Was it because an error was thrown, and the error was docker.errors.APIError, even though it did not end up meaning that the image was not found, but it was thrown for another reason?
- Was it because the image on dockerhub had actually been deleted or similar?
- Does this relate to what @clkao found in #40?
- Was it because the chartpress version we use in z2jh differed from the one in chartpress master?

**Comment by rodriguez-facundo** [comment] 2019-09-09 16:27
Sorry guys, the tag override was not the issue. I have Codefresh lowercasing image tags and k8s was trying to pull an image with a tag that did not exist.

**Comment by consideRatio** [comment] 2019-09-09 16:38
@rodriguez-facundo ah, so your issue is resolved, thats great! But it is still wierd that we ended up with an overridden version of the image which you noted.

**Comment by minrk** [comment] 2019-10-17 13:31
> Was it because memoization through the functools @lru_cache() somehow returned a cached truthy value while it shouldn't have?

I don't think so, because memoization is only for the lifetime of the current process. It doesn't persist across calls or travis jobs

> Was it because an error was thrown, and the error was docker.errors.APIError, even though it did not end up meaning that the image was not found, but it was thrown for another reason?

That could be, but I think it's #40

> Does this relate to what @clkao found in #40?

I think that's exactly it. `image_needs_pushing` is getting the wrong answer thanks to the registry mirror.

**Comment by minrk** [comment] 2019-10-17 13:31
Let's close this as duplicate of #40

**Closed by minrk** 2019-10-17 13:31 UTC
